[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_system = "7a6GBPdjMAfHTKtE4BqzDaynLUBLXpWzSJsVaAo5rMgj"

[programs.devnet]
escrow_system = "7a6GBPdjMAfHTKtE4BqzDaynLUBLXpWzSJsVaAo5rMgj"

[programs.mainnet]
escrow_system = "7a6GBPdjMAfHTKtE4BqzDaynLUBLXpWzSJsVaAo5rMgj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[build]
exclude = ["node_modules"]
