name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          profile: minimal
          override: true
      
      - name: Setup Solana
        uses: solana-labs/solana-verify-action@v1
        with:
          solana_cli_version: 1.18.22
      
      - name: Install Anchor CLI
        run: |
          npm install -g @coral-xyz/anchor-cli@0.31.1
          anchor --version
      
      - name: Setup Solana keypair
        run: |
          solana-keygen new --no-bip39-passphrase --force
          solana config get
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build program
        run: anchor build
      
      - name: Run tests
        run: anchor test --skip-local-validator

  deploy-devnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          profile: minimal
          override: true
      
      - name: Setup Solana
        uses: solana-labs/solana-verify-action@v1
        with:
          solana_cli_version: 1.18.22
      
      - name: Install Anchor CLI
        run: npm install -g @coral-xyz/anchor-cli@0.31.1
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to devnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.DEVNET_DEPLOY_KEYPAIR }}
        run: |
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url devnet
          anchor deploy --provider.cluster devnet

  deploy-mainnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: mainnet
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          profile: minimal
          override: true
      
      - name: Setup Solana
        uses: solana-labs/solana-verify-action@v1
        with:
          solana_cli_version: 1.18.22
      
      - name: Install Anchor CLI
        run: npm install -g @coral-xyz/anchor-cli@0.31.1
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to mainnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.MAINNET_DEPLOY_KEYPAIR }}
        run: |
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url mainnet-beta
          anchor deploy --provider.cluster mainnet-beta
