name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SOLANA_VERSION: "2.2.21"
  ANCHOR_VERSION: "0.31.1"
  RUST_VERSION: "1.82.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ env.RUST_VERSION }}-anchor-${{ env.ANCHOR_VERSION }}
      
      - name: Cache Solana
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-${{ env.SOLANA_VERSION }}
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI
        run: |
          # Try different approaches to install anchor
          if ! command -v anchor &> /dev/null; then
            echo "Installing Anchor CLI..."
            
            # Method 1: Try precompiled binary from solana-foundation
            wget -O /tmp/anchor.tar.bz2 "https://github.com/solana-foundation/anchor/releases/download/v${{ env.ANCHOR_VERSION }}/anchor-cli-v${{ env.ANCHOR_VERSION }}-x86_64-unknown-linux-gnu.tar.bz2" || \
            
            # Method 2: Try from coral-xyz releases  
            wget -O /tmp/anchor.tar.bz2 "https://github.com/coral-xyz/anchor/releases/download/v${{ env.ANCHOR_VERSION }}/anchor-cli-v${{ env.ANCHOR_VERSION }}-x86_64-unknown-linux-gnu.tar.bz2" || \
            
            # Method 3: Build from source with newer Rust
            (echo "Building from source..." && cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v${{ env.ANCHOR_VERSION }} --locked)
            
            # Extract if downloaded
            if [ -f /tmp/anchor.tar.bz2 ]; then
              cd /tmp
              tar -xjf anchor.tar.bz2
              mkdir -p ~/.cargo/bin
              mv anchor ~/.cargo/bin/anchor
              chmod +x ~/.cargo/bin/anchor
            fi
          fi
      
      - name: Verify installations
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          anchor --version || ~/.cargo/bin/anchor --version
      
      - name: Setup Solana keypair
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase --force
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build program
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          if command -v anchor &> /dev/null; then
            anchor build
          else
            ~/.cargo/bin/anchor build
          fi
      
      - name: Run tests
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          if command -v anchor &> /dev/null; then
            anchor test --skip-local-validator
          else
            ~/.cargo/bin/anchor test --skip-local-validator
          fi

  deploy-devnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v${{ env.ANCHOR_VERSION }} --locked
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to devnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.DEVNET_DEPLOY_KEYPAIR }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url devnet
          anchor deploy --provider.cluster devnet

  deploy-mainnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: mainnet
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v${{ env.ANCHOR_VERSION }} --locked
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to mainnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.MAINNET_DEPLOY_KEYPAIR }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url mainnet-beta
          anchor deploy --provider.cluster mainnet-beta
