name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SOLANA_VERSION: "2.2.21"
  ANCHOR_VERSION: "0.31.1"
  RUST_VERSION: "1.81.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache Solana
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-${{ env.SOLANA_VERSION }}
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI precompiled
        run: |
          wget -O anchor-cli.tar.bz2 https://github.com/coral-xyz/anchor/releases/download/v${{ env.ANCHOR_VERSION }}/anchor-cli-v${{ env.ANCHOR_VERSION }}-x86_64-unknown-linux-gnu.tar.bz2
          tar -xjf anchor-cli.tar.bz2
          sudo mv anchor ~/.cargo/bin/anchor
          chmod +x ~/.cargo/bin/anchor
      
      - name: Verify installations
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          ~/.cargo/bin/anchor --version
      
      - name: Setup Solana keypair
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase --force
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build program
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          ~/.cargo/bin/anchor build
      
      - name: Run tests
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          ~/.cargo/bin/anchor test --skip-local-validator

  deploy-devnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI precompiled
        run: |
          wget -O anchor-cli.tar.bz2 https://github.com/coral-xyz/anchor/releases/download/v${{ env.ANCHOR_VERSION }}/anchor-cli-v${{ env.ANCHOR_VERSION }}-x86_64-unknown-linux-gnu.tar.bz2
          tar -xjf anchor-cli.tar.bz2
          sudo mv anchor ~/.cargo/bin/anchor
          chmod +x ~/.cargo/bin/anchor
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to devnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.DEVNET_DEPLOY_KEYPAIR }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url devnet
          ~/.cargo/bin/anchor deploy --provider.cluster devnet

  deploy-mainnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: mainnet
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      
      - name: Install Solana
        run: |
          curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Anchor CLI precompiled
        run: |
          wget -O anchor-cli.tar.bz2 https://github.com/coral-xyz/anchor/releases/download/v${{ env.ANCHOR_VERSION }}/anchor-cli-v${{ env.ANCHOR_VERSION }}-x86_64-unknown-linux-gnu.tar.bz2
          tar -xjf anchor-cli.tar.bz2
          sudo mv anchor ~/.cargo/bin/anchor
          chmod +x ~/.cargo/bin/anchor
      
      - name: Install dependencies
        run: yarn install
      
      - name: Deploy to mainnet
        env:
          DEPLOY_KEYPAIR: ${{ secrets.MAINNET_DEPLOY_KEYPAIR }}
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$DEPLOY_KEYPAIR" > keypair.json
          solana config set --keypair keypair.json --url mainnet-beta
          ~/.cargo/bin/anchor deploy --provider.cluster mainnet-beta
